"""global-nvd-cve provider.

NIST National Vulnerability Database CVE 2.0 API — search and fetch CVE records by keyword, CPE name, CVSS v3 severity, or publish/modify date range. Includes CVE change history.

Homepage: https://nvd.nist.gov/developers/vulnerabilities

Auto-generated by tools/generate_provider.py.
"""


import logging
from typing import Any, List, Optional, Sequence

import mcp.types as types
from pydantic import BaseModel, Field

from meta_data_mcp.utils import (
    create_mcp_server,
    http_get,
    run_server,
    serialize_for_llm,
)


log = logging.getLogger(__name__)

BASE_URL = "https://services.nvd.nist.gov"

RESOURCES: List[Any] = []
RESOURCES_HANDLERS: dict[str, Any] = {}
TOOLS: List[types.Tool] = []
TOOLS_HANDLERS: dict[str, Any] = {}


###################
# nvd-search-cves
###################


class NvdSearchCvesParams(BaseModel):
    """Parameters for nvd-search-cves."""

    keywordSearch: Optional[str] = Field(
        None,
        description="Free-text search across CVE descriptions (e.g. 'log4j RCE').",
    )

    cveId: Optional[str] = Field(
        None,
        description="Specific CVE id (e.g. CVE-2024-1234) — returns just that one record.",
    )

    cpeName: Optional[str] = Field(
        None,
        description="CPE 2.3 name filter, e.g. cpe:2.3:o:linux:linux_kernel:6.6.1:*:*:*:*:*:*:*",
    )

    cvssV3Severity: Optional[str] = Field(
        None,
        description="Severity bucket: NONE, LOW, MEDIUM, HIGH, or CRITICAL.",
    )

    pubStartDate: Optional[str] = Field(
        None,
        description="ISO 8601 (e.g. 2024-01-01T00:00:00.000) — CVEs published on/after this date.",
    )

    pubEndDate: Optional[str] = Field(
        None,
        description="ISO 8601 — CVEs published on/before this date.",
    )

    lastModStartDate: Optional[str] = Field(
        None,
        description="ISO 8601 — CVEs last-modified on/after this date.",
    )

    lastModEndDate: Optional[str] = Field(
        None,
        description="ISO 8601 — CVEs last-modified on/before this date.",
    )

    resultsPerPage: Optional[int] = Field(
        20,
        description="Results per page (max 2000).",
    )

    startIndex: Optional[int] = Field(
        0,
        description="Offset for pagination (0-indexed).",
    )


def fetch_nvd_search_cves(params: NvdSearchCvesParams) -> Any:
    """Fetch data for the nvd-search-cves tool."""
    url = f"{BASE_URL}/rest/json/cves/2.0"
    query: dict = {}
    if params.keywordSearch is not None:
        query["keywordSearch"] = params.keywordSearch
    if params.cveId is not None:
        query["cveId"] = params.cveId
    if params.cpeName is not None:
        query["cpeName"] = params.cpeName
    if params.cvssV3Severity is not None:
        query["cvssV3Severity"] = params.cvssV3Severity
    if params.pubStartDate is not None:
        query["pubStartDate"] = params.pubStartDate
    if params.pubEndDate is not None:
        query["pubEndDate"] = params.pubEndDate
    if params.lastModStartDate is not None:
        query["lastModStartDate"] = params.lastModStartDate
    if params.lastModEndDate is not None:
        query["lastModEndDate"] = params.lastModEndDate
    if params.resultsPerPage is not None:
        query["resultsPerPage"] = params.resultsPerPage
    if params.startIndex is not None:
        query["startIndex"] = params.startIndex
    response = http_get(url, params=query or None)
    return response.json()


async def handle_nvd_search_cves(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the nvd-search-cves tool call."""
    try:
        params = NvdSearchCvesParams(**(arguments or {}))
        data = fetch_nvd_search_cves(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling nvd-search-cves: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="nvd-search-cves",
        description="Search the NVD CVE 2.0 database. Combine any of: keywordSearch (free-text), cpeName (CPE 2.3), cvssV3Severity (NONE|LOW|MEDIUM|HIGH|CRITICAL), pubStartDate/pubEndDate, lastModStartDate/lastModEndDate. Returns up to 2000 results per page; paginate with startIndex.",
        inputSchema=NvdSearchCvesParams.model_json_schema(),
    )
)
TOOLS_HANDLERS["nvd-search-cves"] = handle_nvd_search_cves


###################
# nvd-get-cve
###################


class NvdGetCveParams(BaseModel):
    """Parameters for nvd-get-cve."""

    cveId: str = Field(
        ...,
        description="CVE id, e.g. CVE-2021-44228.",
    )


def fetch_nvd_get_cve(params: NvdGetCveParams) -> Any:
    """Fetch data for the nvd-get-cve tool."""
    url = f"{BASE_URL}/rest/json/cves/2.0"
    query: dict = {}
    query["cveId"] = params.cveId
    response = http_get(url, params=query or None)
    return response.json()


async def handle_nvd_get_cve(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the nvd-get-cve tool call."""
    try:
        params = NvdGetCveParams(**(arguments or {}))
        data = fetch_nvd_get_cve(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling nvd-get-cve: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="nvd-get-cve",
        description="Fetch a single CVE record by id. Convenience wrapper over search.",
        inputSchema=NvdGetCveParams.model_json_schema(),
    )
)
TOOLS_HANDLERS["nvd-get-cve"] = handle_nvd_get_cve


###################
# nvd-cve-history
###################


class NvdCveHistoryParams(BaseModel):
    """Parameters for nvd-cve-history."""

    cveId: Optional[str] = Field(
        None,
        description="Specific CVE id.",
    )

    changeStartDate: Optional[str] = Field(
        None,
        description="ISO 8601 — changes on/after this date.",
    )

    changeEndDate: Optional[str] = Field(
        None,
        description="ISO 8601 — changes on/before this date.",
    )

    resultsPerPage: Optional[int] = Field(
        20,
        description="Results per page.",
    )

    startIndex: Optional[int] = Field(
        0,
        description="Offset for pagination.",
    )


def fetch_nvd_cve_history(params: NvdCveHistoryParams) -> Any:
    """Fetch data for the nvd-cve-history tool."""
    url = f"{BASE_URL}/rest/json/cvehistory/2.0"
    query: dict = {}
    if params.cveId is not None:
        query["cveId"] = params.cveId
    if params.changeStartDate is not None:
        query["changeStartDate"] = params.changeStartDate
    if params.changeEndDate is not None:
        query["changeEndDate"] = params.changeEndDate
    if params.resultsPerPage is not None:
        query["resultsPerPage"] = params.resultsPerPage
    if params.startIndex is not None:
        query["startIndex"] = params.startIndex
    response = http_get(url, params=query or None)
    return response.json()


async def handle_nvd_cve_history(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the nvd-cve-history tool call."""
    try:
        params = NvdCveHistoryParams(**(arguments or {}))
        data = fetch_nvd_cve_history(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling nvd-cve-history: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="nvd-cve-history",
        description="List CVE change-history events. Filter by CVE id or change date range; paginate with startIndex.",
        inputSchema=NvdCveHistoryParams.model_json_schema(),
    )
)
TOOLS_HANDLERS["nvd-cve-history"] = handle_nvd_cve_history


async def main(transport: str = "stdio", port: int = 8000, host: str = "127.0.0.1"):
    server = create_mcp_server(
        "global-nvd-cve",
        RESOURCES,
        RESOURCES_HANDLERS,
        TOOLS,
        TOOLS_HANDLERS,
    )
    await run_server(server, transport, port, host)


if __name__ == "__main__":
    import anyio

    anyio.run(main)
