"""us-arcgis-item provider.

Generic ArcGIS public item metadata provider.

Homepage: https://developers.arcgis.com/rest/users-groups-and-items/item/

Auto-generated by tools/generate_provider.py.
"""


import logging
from typing import Any, List, Optional, Sequence

import mcp.types as types
from pydantic import BaseModel, Field

from meta_data_mcp.utils import (
    create_mcp_server,
    http_get,
    run_server,
    serialize_for_llm,
)


log = logging.getLogger(__name__)

BASE_URL = "https://www.arcgis.com"

RESOURCES: List[Any] = []
RESOURCES_HANDLERS: dict[str, Any] = {}
TOOLS: List[types.Tool] = []
TOOLS_HANDLERS: dict[str, Any] = {}


###################
# us-arcgis-get-item
###################


class UsArcgisGetItemParams(BaseModel):
    """Parameters for us-arcgis-get-item."""

    item_id: str = Field(
        ...,
        description="ArcGIS item id.",
    )

    f: Optional[str] = Field(
        "json",
        description="ArcGIS response format.",
    )


def fetch_us_arcgis_get_item(params: UsArcgisGetItemParams) -> Any:
    """Fetch data for the us-arcgis-get-item tool."""
    url = f"{BASE_URL}/sharing/rest/content/items/{params.item_id}"
    query: dict = {}
    if params.f is not None:
        query["f"] = params.f
    response = http_get(url, params=query or None)
    return response.json()


async def handle_us_arcgis_get_item(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the us-arcgis-get-item tool call."""
    try:
        params = UsArcgisGetItemParams(**(arguments or {}))
        data = fetch_us_arcgis_get_item(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling us-arcgis-get-item: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="us-arcgis-get-item",
        description="Fetch public ArcGIS item metadata by item id.",
        inputSchema=UsArcgisGetItemParams.model_json_schema(),
    )
)
TOOLS_HANDLERS["us-arcgis-get-item"] = handle_us_arcgis_get_item


async def main(transport: str = "stdio", port: int = 8000, host: str = "127.0.0.1"):
    server = create_mcp_server(
        "us-arcgis-item",
        RESOURCES,
        RESOURCES_HANDLERS,
        TOOLS,
        TOOLS_HANDLERS,
    )
    await run_server(server, transport, port, host)


if __name__ == "__main__":
    import anyio

    anyio.run(main)
