"""us-ncdeq-gis provider.

NCDEQ / NC DENR ArcGIS Hub environmental GIS open data.

Homepage: https://data-ncdenr.opendata.arcgis.com

Auto-generated by tools/generate_provider.py.
"""


import logging
from typing import Any, List, Optional, Sequence

import mcp.types as types
from pydantic import BaseModel, Field

from meta_data_mcp.utils import (
    create_mcp_server,
    http_get,
    run_server,
    serialize_for_llm,
)


log = logging.getLogger(__name__)

BASE_URL = "https://data-ncdenr.opendata.arcgis.com"

RESOURCES: List[Any] = []
RESOURCES_HANDLERS: dict[str, Any] = {}
TOOLS: List[types.Tool] = []
TOOLS_HANDLERS: dict[str, Any] = {}


###################
# us-ncdeq-search-catalog
###################


class UsNcdeqSearchCatalogParams(BaseModel):
    """Parameters for us-ncdeq-search-catalog."""

    q: Optional[str] = Field(
        None,
        description="Free-text catalog query.",
    )

    num: Optional[int] = Field(
        20,
        description="Maximum search results.",
    )


def fetch_us_ncdeq_search_catalog(params: UsNcdeqSearchCatalogParams) -> Any:
    """Fetch data for the us-ncdeq-search-catalog tool."""
    url = f"{BASE_URL}/api/search/v1"
    query: dict = {}
    if params.q is not None:
        query["q"] = params.q
    if params.num is not None:
        query["num"] = params.num
    response = http_get(url, params=query or None)
    return response.json()


async def handle_us_ncdeq_search_catalog(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the us-ncdeq-search-catalog tool call."""
    try:
        params = UsNcdeqSearchCatalogParams(**(arguments or {}))
        data = fetch_us_ncdeq_search_catalog(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling us-ncdeq-search-catalog: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="us-ncdeq-search-catalog",
        description="Search NCDEQ / NC DENR ArcGIS Hub catalog.",
        inputSchema=UsNcdeqSearchCatalogParams.model_json_schema(),
    )
)
TOOLS_HANDLERS["us-ncdeq-search-catalog"] = handle_us_ncdeq_search_catalog


async def main(transport: str = "stdio", port: int = 8000, host: str = "127.0.0.1"):
    server = create_mcp_server(
        "us-ncdeq-gis",
        RESOURCES,
        RESOURCES_HANDLERS,
        TOOLS,
        TOOLS_HANDLERS,
    )
    await run_server(server, transport, port, host)


if __name__ == "__main__":
    import anyio

    anyio.run(main)
