"""us-ncdeq-gis provider.

NCDEQ / NC DENR ArcGIS Hub environmental GIS open data.

Homepage: https://data-ncdenr.opendata.arcgis.com

Auto-generated by tools/generate_provider.py.
"""

import logging
from typing import Any, List, Optional, Sequence

import mcp.types as types
from pydantic import BaseModel, Field

from meta_data_mcp.ui_resources.shape_records_v1 import URI as RECORDS_URI
from meta_data_mcp.utils import (
    to_records_text,
    create_mcp_server,
    http_get,
    run_server,
)


log = logging.getLogger(__name__)

PROVIDER_ID = "us-ncdeq-gis"
BASE_URL = "https://data-ncdenr.opendata.arcgis.com"

# Records-shape adapter constants
_MAX_DESC_CHARS = 500

RESOURCES: List[Any] = []
RESOURCES_HANDLERS: dict[str, Any] = {}
TOOLS: List[types.Tool] = []
TOOLS_HANDLERS: dict[str, Any] = {}


###################
# us-ncdeq-search-catalog
###################


class UsNcdeqSearchCatalogParams(BaseModel):
    """Parameters for us-ncdeq-search-catalog."""

    q: Optional[str] = Field(
        None,
        description="Free-text catalog query.",
    )

    num: Optional[int] = Field(
        20,
        description="Maximum search results.",
    )


def fetch_us_ncdeq_search_catalog(params: UsNcdeqSearchCatalogParams) -> Any:
    """Fetch data for the us-ncdeq-search-catalog tool."""
    url = f"{BASE_URL}/api/search/v1"
    query: dict = {}
    if params.q is not None:
        query["q"] = params.q
    if params.num is not None:
        query["num"] = params.num
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


def _arcgis_search_to_shape_payload(data: Any) -> dict:
    """Adapt an ArcGIS Hub ``/api/search/v1`` JSON-API response to the
    ``ui://meta-data-mcp/shape/records/v1`` payload.

    ArcGIS returns ``{data: [{id, type, attributes: {...}}], meta}``;
    we hoist the relevant attributes (name, type, owner, tags, source,
    timestamps) to top-level columns.
    """
    raw_rows = data.get("data", []) if isinstance(data, dict) else []
    rows: list[dict[str, Any]] = []
    for entry in raw_rows:
        if not isinstance(entry, dict):
            continue
        attrs = entry.get("attributes") or {}
        if not isinstance(attrs, dict):
            attrs = {}
        tags = attrs.get("tags") or []
        tag_csv = (
            ", ".join(t for t in tags if isinstance(t, str))
            if isinstance(tags, list)
            else ""
        )
        snippet = attrs.get("snippet") or attrs.get("description") or ""
        if isinstance(snippet, str) and len(snippet) > _MAX_DESC_CHARS:
            snippet = snippet[:_MAX_DESC_CHARS].rstrip() + "…"
        rows.append(
            {
                "id": entry.get("id"),
                "name": attrs.get("name") or attrs.get("title"),
                "type": entry.get("type") or attrs.get("type"),
                "owner": attrs.get("owner"),
                "source": attrs.get("source"),
                "tags": tag_csv,
                "created": attrs.get("created"),
                "modified": attrs.get("modified"),
                "url": attrs.get("url"),
                "description": snippet,
            }
        )
    return {
        "rows": rows,
        "schema": {
            "columns": [
                {"name": "id", "type": "string", "description": "ArcGIS item id"},
                {"name": "name", "type": "string", "description": "Item name/title"},
                {"name": "type", "type": "string", "description": "ArcGIS item type"},
                {"name": "owner", "type": "string", "description": "Owner"},
                {"name": "source", "type": "string", "description": "Source"},
                {"name": "tags", "type": "string", "description": "Tags (csv)"},
                {
                    "name": "created",
                    "type": "number",
                    "description": "Created at (epoch)",
                },
                {
                    "name": "modified",
                    "type": "number",
                    "description": "Modified at (epoch)",
                },
                {"name": "url", "type": "string", "description": "Source URL"},
                {
                    "name": "description",
                    "type": "string",
                    "description": "Snippet (truncated)",
                },
            ]
        },
        "default_facets": ["type", "owner", "source"],
    }


async def handle_us_ncdeq_search_catalog(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the us-ncdeq-search-catalog tool call.

    Returns the response in the records shape primitive payload.
    """
    try:
        params = UsNcdeqSearchCatalogParams(**(arguments or {}))
        data = fetch_us_ncdeq_search_catalog(params)
        payload = _arcgis_search_to_shape_payload(data)
        return [types.TextContent(type="text", text=to_records_text(payload))]
    except Exception as e:
        log.error(f"Error handling us-ncdeq-search-catalog: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="us-ncdeq-search-catalog",
        description="Search NCDEQ / NC DENR ArcGIS Hub catalog.",
        inputSchema=UsNcdeqSearchCatalogParams.model_json_schema(),
        _meta={"ui": {"resourceUri": RECORDS_URI}},
    )
)
TOOLS_HANDLERS["us-ncdeq-search-catalog"] = handle_us_ncdeq_search_catalog


async def main(transport: str = "stdio", port: int = 8000, host: str = "127.0.0.1"):
    server = create_mcp_server(
        "us-ncdeq-gis",
        RESOURCES,
        RESOURCES_HANDLERS,
        TOOLS,
        TOOLS_HANDLERS,
    )
    await run_server(server, transport, port, host)


if __name__ == "__main__":
    import anyio

    anyio.run(main)
