"""us-raleigh provider.

City of Raleigh Socrata-backed open data provider.

Homepage: https://data.raleighnc.gov

Auto-generated by tools/generate_provider.py.
"""

import logging
from typing import Any, List, Optional, Sequence

import mcp.types as types
from pydantic import BaseModel, Field

from meta_data_mcp.ui_resources.shape_records_v1 import URI as RECORDS_URI
from meta_data_mcp.utils import (
    to_records_text,
    create_mcp_server,
    http_get,
    run_server,
    serialize_for_llm,
)


log = logging.getLogger(__name__)

PROVIDER_ID = "us-raleigh"
BASE_URL = "https://data.raleighnc.gov"

# Records-shape adapter constants
_MAX_DESC_CHARS = 500

RESOURCES: List[Any] = []
RESOURCES_HANDLERS: dict[str, Any] = {}
TOOLS: List[types.Tool] = []
TOOLS_HANDLERS: dict[str, Any] = {}


###################
# us-raleigh-search-catalog
###################


class UsRaleighSearchCatalogParams(BaseModel):
    """Parameters for us-raleigh-search-catalog."""

    q: Optional[str] = Field(
        None,
        description="Free-text catalog query.",
    )

    limit: Optional[int] = Field(
        20,
        description="Maximum catalog results.",
    )


def fetch_us_raleigh_search_catalog(params: UsRaleighSearchCatalogParams) -> Any:
    """Fetch data for the us-raleigh-search-catalog tool."""
    url = f"{BASE_URL}/api/views"
    query: dict = {}
    if params.q is not None:
        query["q"] = params.q
    if params.limit is not None:
        query["limit"] = params.limit
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


def _socrata_views_to_shape_payload(data: Any) -> dict:
    """Adapt a Socrata ``/api/views`` response to the records shape
    primitive's payload (identical to peer Socrata adapters)."""
    raw_rows = data if isinstance(data, list) else []
    rows: list[dict[str, Any]] = []
    for view in raw_rows:
        if not isinstance(view, dict):
            continue
        owner = view.get("owner") or {}
        owner_name = (
            (owner.get("displayName") or owner.get("screenName"))
            if isinstance(owner, dict)
            else None
        )
        tags = view.get("tags") or []
        tag_csv = (
            ", ".join(t for t in tags if isinstance(t, str))
            if isinstance(tags, list)
            else ""
        )
        desc = view.get("description") or ""
        if isinstance(desc, str) and len(desc) > _MAX_DESC_CHARS:
            desc = desc[:_MAX_DESC_CHARS].rstrip() + "…"
        rows.append(
            {
                "id": view.get("id"),
                "name": view.get("name"),
                "category": view.get("category"),
                "attribution": view.get("attribution"),
                "owner": owner_name,
                "viewType": view.get("viewType"),
                "tags": tag_csv,
                "rowsUpdatedAt": view.get("rowsUpdatedAt"),
                "createdAt": view.get("createdAt"),
                "description": desc,
            }
        )
    return {
        "rows": rows,
        "schema": {
            "columns": [
                {"name": "id", "type": "string", "description": "Socrata dataset id"},
                {"name": "name", "type": "string", "description": "Dataset name"},
                {
                    "name": "category",
                    "type": "string",
                    "description": "Catalog category",
                },
                {
                    "name": "attribution",
                    "type": "string",
                    "description": "Attribution",
                },
                {"name": "owner", "type": "string", "description": "Owner name"},
                {
                    "name": "viewType",
                    "type": "string",
                    "description": "Socrata view type",
                },
                {"name": "tags", "type": "string", "description": "Tags (csv)"},
                {
                    "name": "rowsUpdatedAt",
                    "type": "number",
                    "description": "Last data update (epoch)",
                },
                {
                    "name": "createdAt",
                    "type": "number",
                    "description": "Created at (epoch)",
                },
                {
                    "name": "description",
                    "type": "string",
                    "description": "Description (truncated)",
                },
            ]
        },
        "default_facets": ["category", "viewType", "attribution"],
    }


async def handle_us_raleigh_search_catalog(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the us-raleigh-search-catalog tool call.

    Returns the response in the records shape primitive payload.
    """
    try:
        params = UsRaleighSearchCatalogParams(**(arguments or {}))
        data = fetch_us_raleigh_search_catalog(params)
        payload = _socrata_views_to_shape_payload(data)
        return [types.TextContent(type="text", text=to_records_text(payload))]
    except Exception as e:
        log.error(f"Error handling us-raleigh-search-catalog: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="us-raleigh-search-catalog",
        description="Search Raleigh open data catalog metadata.",
        inputSchema=UsRaleighSearchCatalogParams.model_json_schema(),
        _meta={"ui": {"resourceUri": RECORDS_URI}},
    )
)
TOOLS_HANDLERS["us-raleigh-search-catalog"] = handle_us_raleigh_search_catalog


###################
# us-raleigh-get-metadata
###################


class UsRaleighGetMetadataParams(BaseModel):
    """Parameters for us-raleigh-get-metadata."""

    dataset_id: str = Field(
        ...,
        description="Socrata dataset id.",
    )


def fetch_us_raleigh_get_metadata(params: UsRaleighGetMetadataParams) -> Any:
    """Fetch data for the us-raleigh-get-metadata tool."""
    url = f"{BASE_URL}/api/views/{params.dataset_id}"
    query: dict = {}
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_us_raleigh_get_metadata(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the us-raleigh-get-metadata tool call."""
    try:
        params = UsRaleighGetMetadataParams(**(arguments or {}))
        data = fetch_us_raleigh_get_metadata(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling us-raleigh-get-metadata: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="us-raleigh-get-metadata",
        description="Fetch Raleigh dataset metadata by Socrata dataset id.",
        inputSchema=UsRaleighGetMetadataParams.model_json_schema(),
    )
)
TOOLS_HANDLERS["us-raleigh-get-metadata"] = handle_us_raleigh_get_metadata


async def main(transport: str = "stdio", port: int = 8000, host: str = "127.0.0.1"):
    server = create_mcp_server(
        "us-raleigh",
        RESOURCES,
        RESOURCES_HANDLERS,
        TOOLS,
        TOOLS_HANDLERS,
    )
    await run_server(server, transport, port, host)


if __name__ == "__main__":
    import anyio

    anyio.run(main)
