"""us-raleigh provider.

City of Raleigh Socrata-backed open data provider.

Homepage: https://data.raleighnc.gov

Auto-generated by tools/generate_provider.py.
"""


import logging
from typing import Any, List, Optional, Sequence

import mcp.types as types
from pydantic import BaseModel, Field

from opendata_mcp.utils import (
    create_mcp_server,
    http_get,
    run_server,
    serialize_for_llm,
)


log = logging.getLogger(__name__)

BASE_URL = "https://data.raleighnc.gov"

RESOURCES: List[Any] = []
RESOURCES_HANDLERS: dict[str, Any] = {}
TOOLS: List[types.Tool] = []
TOOLS_HANDLERS: dict[str, Any] = {}


###################
# us-raleigh-search-catalog
###################


class UsRaleighSearchCatalogParams(BaseModel):
    """Parameters for us-raleigh-search-catalog."""

    q: Optional[str] = Field(
        None,
        description="Free-text catalog query.",
    )

    limit: Optional[int] = Field(
        20,
        description="Maximum catalog results.",
    )


def fetch_us_raleigh_search_catalog(params: UsRaleighSearchCatalogParams) -> Any:
    """Fetch data for the us-raleigh-search-catalog tool."""
    url = f"{BASE_URL}/api/views"
    query: dict = {}
    if params.q is not None:
        query["q"] = params.q
    if params.limit is not None:
        query["limit"] = params.limit
    response = http_get(url, params=query or None)
    return response.json()


async def handle_us_raleigh_search_catalog(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the us-raleigh-search-catalog tool call."""
    try:
        params = UsRaleighSearchCatalogParams(**(arguments or {}))
        data = fetch_us_raleigh_search_catalog(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling us-raleigh-search-catalog: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="us-raleigh-search-catalog",
        description="Search Raleigh open data catalog metadata.",
        inputSchema=UsRaleighSearchCatalogParams.model_json_schema(),
    )
)
TOOLS_HANDLERS["us-raleigh-search-catalog"] = handle_us_raleigh_search_catalog


###################
# us-raleigh-get-metadata
###################


class UsRaleighGetMetadataParams(BaseModel):
    """Parameters for us-raleigh-get-metadata."""

    dataset_id: str = Field(
        ...,
        description="Socrata dataset id.",
    )


def fetch_us_raleigh_get_metadata(params: UsRaleighGetMetadataParams) -> Any:
    """Fetch data for the us-raleigh-get-metadata tool."""
    url = f"{BASE_URL}/api/views/{params.dataset_id}"
    query: dict = {}
    response = http_get(url, params=query or None)
    return response.json()


async def handle_us_raleigh_get_metadata(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the us-raleigh-get-metadata tool call."""
    try:
        params = UsRaleighGetMetadataParams(**(arguments or {}))
        data = fetch_us_raleigh_get_metadata(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling us-raleigh-get-metadata: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="us-raleigh-get-metadata",
        description="Fetch Raleigh dataset metadata by Socrata dataset id.",
        inputSchema=UsRaleighGetMetadataParams.model_json_schema(),
    )
)
TOOLS_HANDLERS["us-raleigh-get-metadata"] = handle_us_raleigh_get_metadata


async def main(transport: str = "stdio", port: int = 8000, host: str = "127.0.0.1"):
    server = create_mcp_server(
        "us-raleigh",
        RESOURCES,
        RESOURCES_HANDLERS,
        TOOLS,
        TOOLS_HANDLERS,
    )
    await run_server(server, transport, port, host)


if __name__ == "__main__":
    import anyio

    anyio.run(main)
