"""Auto-generated tests for the us-nc-onemap provider.

Generated by tools/generate_provider.py — feel free to extend with
tool-specific assertions once the provider stabilizes.
"""

from unittest.mock import Mock, patch

import httpx
import pytest

from meta_data_mcp.providers.us_nc_onemap import (
    handle_us_nc_onemap_list_services,
)


@pytest.fixture
def anyio_backend():
    return "asyncio"


@pytest.mark.anyio
async def test_us_nc_onemap_list_services_success():
    """Smoke test: us-nc-onemap-list-services returns success payload."""
    with patch("httpx.get") as mock_get:
        mock_get.return_value.json.return_value = {
            "ok": True,
            "marker": "GENERATED_TEST_MARKER",
        }
        mock_get.return_value.raise_for_status = Mock()
        mock_get.return_value.status_code = 200
        result = await handle_us_nc_onemap_list_services({})
        assert len(result) == 1
        assert "GENERATED_TEST_MARKER" in result[0].text


@pytest.mark.anyio
async def test_us_nc_onemap_list_services_http_error():
    """us-nc-onemap-list-services propagates httpx errors."""
    with patch("httpx.get") as mock_get:
        mock_get.side_effect = httpx.HTTPError("Network down")
        with pytest.raises(httpx.HTTPError):
            await handle_us_nc_onemap_list_services({})
