"""Auto-generated tests for the us-healthdata-gov provider.

Generated by tools/generate_provider.py — feel free to extend with
tool-specific assertions once the provider stabilizes.
"""

from unittest.mock import Mock, patch

import httpx
import pytest

from meta_data_mcp.providers.us_healthdata_gov import (
    handle_us_healthdata_search_catalog,
    handle_us_healthdata_get_metadata,
)


@pytest.fixture
def anyio_backend():
    return "asyncio"


@pytest.mark.anyio
async def test_us_healthdata_search_catalog_success():
    """Smoke test: us-healthdata-search-catalog returns success payload."""
    with patch("httpx.get") as mock_get:
        mock_get.return_value.json.return_value = {
            "ok": True,
            "marker": "GENERATED_TEST_MARKER",
        }
        mock_get.return_value.raise_for_status = Mock()
        mock_get.return_value.status_code = 200
        result = await handle_us_healthdata_search_catalog({})
        assert len(result) == 1
        assert "GENERATED_TEST_MARKER" in result[0].text


@pytest.mark.anyio
async def test_us_healthdata_search_catalog_http_error():
    """us-healthdata-search-catalog propagates httpx errors."""
    with patch("httpx.get") as mock_get:
        mock_get.side_effect = httpx.HTTPError("Network down")
        with pytest.raises(httpx.HTTPError):
            await handle_us_healthdata_search_catalog({})


@pytest.mark.anyio
async def test_us_healthdata_get_metadata_success():
    """Smoke test: us-healthdata-get-metadata returns success payload."""
    with patch("httpx.get") as mock_get:
        mock_get.return_value.json.return_value = {
            "ok": True,
            "marker": "GENERATED_TEST_MARKER",
        }
        mock_get.return_value.raise_for_status = Mock()
        mock_get.return_value.status_code = 200
        result = await handle_us_healthdata_get_metadata({"dataset_id": "test"})
        assert len(result) == 1
        assert "GENERATED_TEST_MARKER" in result[0].text


@pytest.mark.anyio
async def test_us_healthdata_get_metadata_http_error():
    """us-healthdata-get-metadata propagates httpx errors."""
    with patch("httpx.get") as mock_get:
        mock_get.side_effect = httpx.HTTPError("Network down")
        with pytest.raises(httpx.HTTPError):
            await handle_us_healthdata_get_metadata({"dataset_id": "test"})
