"""Auto-generated tests for the global-nvd-cve provider.

Generated by tools/generate_provider.py — feel free to extend with
tool-specific assertions once the provider stabilizes.
"""

from unittest.mock import Mock, patch

import httpx
import pytest

from meta_data_mcp.providers.global_nvd_cve import (
    TOOLS,
    handle_nvd_search_cves,
    handle_nvd_get_cve,
    handle_nvd_cve_history,
)
from meta_data_mcp.ui_resources.app_vulnerability_v1 import URI as VULN_URI


@pytest.fixture
def anyio_backend():
    return "asyncio"


@pytest.mark.anyio
async def test_nvd_search_cves_success():
    """Smoke test: nvd-search-cves returns success payload."""
    with patch("httpx.get") as mock_get:
        mock_get.return_value.json.return_value = {
            "ok": True,
            "marker": "GENERATED_TEST_MARKER",
        }
        mock_get.return_value.raise_for_status = Mock()
        mock_get.return_value.status_code = 200
        result = await handle_nvd_search_cves({})
        assert len(result) == 1
        assert "GENERATED_TEST_MARKER" in result[0].text


@pytest.mark.anyio
async def test_nvd_search_cves_http_error():
    """nvd-search-cves propagates httpx errors."""
    with patch("httpx.get") as mock_get:
        mock_get.side_effect = httpx.HTTPError("Network down")
        with pytest.raises(httpx.HTTPError):
            await handle_nvd_search_cves({})


@pytest.mark.anyio
async def test_nvd_get_cve_success():
    """Smoke test: nvd-get-cve returns success payload."""
    with patch("httpx.get") as mock_get:
        mock_get.return_value.json.return_value = {
            "ok": True,
            "marker": "GENERATED_TEST_MARKER",
        }
        mock_get.return_value.raise_for_status = Mock()
        mock_get.return_value.status_code = 200
        result = await handle_nvd_get_cve({"cveId": "test"})
        assert len(result) == 1
        assert "GENERATED_TEST_MARKER" in result[0].text


@pytest.mark.anyio
async def test_nvd_get_cve_http_error():
    """nvd-get-cve propagates httpx errors."""
    with patch("httpx.get") as mock_get:
        mock_get.side_effect = httpx.HTTPError("Network down")
        with pytest.raises(httpx.HTTPError):
            await handle_nvd_get_cve({"cveId": "test"})


@pytest.mark.anyio
async def test_nvd_cve_history_success():
    """Smoke test: nvd-cve-history returns success payload."""
    with patch("httpx.get") as mock_get:
        mock_get.return_value.json.return_value = {
            "ok": True,
            "marker": "GENERATED_TEST_MARKER",
        }
        mock_get.return_value.raise_for_status = Mock()
        mock_get.return_value.status_code = 200
        result = await handle_nvd_cve_history({})
        assert len(result) == 1
        assert "GENERATED_TEST_MARKER" in result[0].text


@pytest.mark.anyio
async def test_nvd_cve_history_http_error():
    """nvd-cve-history propagates httpx errors."""
    with patch("httpx.get") as mock_get:
        mock_get.side_effect = httpx.HTTPError("Network down")
        with pytest.raises(httpx.HTTPError):
            await handle_nvd_cve_history({})


# ---------------------------------------------------------------------------
# Phase 5: MCP Apps shape primitive binding (vulnerability app).
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "tool_name", ["nvd-search-cves", "nvd-get-cve", "nvd-cve-history"]
)
def test_nvd_tool_binds_to_vulnerability_app(tool_name):
    """Each NVD tool must declare ``_meta.ui.resourceUri`` pointing at
    the canonical vulnerability app URI. Pin both the Python-side
    ``.meta`` attribute AND the wire-level alias (``model_dump(
    by_alias=True)`` emits ``_meta``) so a future SDK regression on the
    populate_by_name footgun is caught here."""
    tool = next(t for t in TOOLS if t.name == tool_name)
    assert tool.meta == {"ui": {"resourceUri": VULN_URI}}, (
        f"{tool_name} is not bound to {VULN_URI}"
    )
    wire = tool.model_dump(by_alias=True, exclude_none=True)
    assert wire.get("_meta", {}).get("ui", {}).get("resourceUri") == VULN_URI
